[package]
name = "rskdl"
version = "0.1.0"
edition = "2021"
authors = ["Dani Smith <code@danini.dev>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.7.1" }
kdl = { version = "6.3.2" }
